language: java
cache:
  directories:
  - $HOME/.m2
jdk: 
  - oraclejdk8
before_install:
  - pip install --user codecov
after_success:
  - codecov
before_script:
  - bundle install --path vendor/bundle/
  - mvn dependency:get -Dartifact=org.seleniumhq.selenium:selenium-server:2.52.0
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "java -jar ~/.m2/repository/org/seleniumhq/selenium/selenium-server/2.52.0/selenium-server-2.52.0.jar > selenium.log 2>&1 &"
  - "java -jar target/sparkrestservice-jar-with-dependencies.jar &"
  - sleep 2
  - curl localhost:4567/companies
script:
  - mvn test
  - bundle exec cucumber --require src/test/resources/features/step_definitions/ src/test/resources/features
